import { MenuItemT } from "@/lib/types/menu";

export const MenuItemData: MenuItemT[] = [
  {
    id: 1,
    title: "اسپرسو",
    description: "تک | دوبل",
    price: "32.000 | 25.000",
    type: "coffee",
  },
  {
    id: 2,
    title: "ایبریک",
    description: "قهوه ترک",
    price: "45.000",
    type: "coffee",
  },
  {
    id: 3,
    title: "لاته",
    description: null,
    price: "50.000",
    type: "coffee",
  },
  {
    id: 4,
    title: "کاپوچینو",
    description: "کوچک | بزرگ",
    price: "50.000 | 35.000",
    type: "coffee",
  },
  {
    id: 5,
    title: "چای ماسالا",
    description: "کوچک | بزرگ",
    price: "50.000 | 35.000",
    type: "coffee",
  },
  {
    id: 6,
    title: "چای فوری",
    description: null,
    price: "20.000",
    type: "coffee",
  },
  {
    id: 7,
    title: "نسکافه",
    description: "قهوه گلد + شیر",
    price: "50.000",
    type: "coffee",
  },
  {
    id: 8,
    title: "هات چاکلت",
    description: "کوچک | بزرگ",
    price: "60.000 | 45.000",
    type: "chocolate",
  },
  {
    id: 9,
    title: "بنانا چاکلت",
    description: "هات چاکلت + تکه‌های موز",
    price: "60.000",
    type: "chocolate",
  },
  {
    id: 11,
    title: "نوتلا چاکلت",
    description: "هات چاکلت + نوتلا",
    price: "90.000",
    type: "chocolate",
  },
  {
    id: 13,
    title: "کارامل ماکیاتو",
    description: "سیروپ کارامل + اسپرسو + شیر",
    price: "60.000",
    type: "chocolate",
  },
  {
    id: 14,
    title: "موکا",
    description: "سیروپ شکلات + اسپرسو + شیر",
    price: "60.000",
    type: "chocolate",
  },
  {
    id: 15,
    title: "هات چیپس",
    description: "عادی | ویژه",
    price: "140.000 | 120.000",
    type: "food",
  },
  {
    id: 16,
    title: "همبرگر",
    description: null,
    price: "140.000",
    type: "food",
  },
  {
    id: 17,
    title: "نیمرو",
    description: null,
    price: "35.000",
    type: "food",
  },
  {
    id: 18,
    title: "املت",
    description: null,
    price: "50.000",
    type: "food",
  },
  {
    id: 19,
    title: "سیب‌زمینی بدون روغن",
    description: "پرس یک‌نفره",
    price: "60.000",
    type: "food",
  },
  {
    id: 20,
    title: "میلک شیک",
    description: "انبه و آناناس | غیره",
    price: "70.000 | 80.000",
    type: "drink",
  },
  {
    id: 21,
    title: "اسموتی",
    description: "موز و توت فرنگی | انبه و آناناس",
    price: "90.000 | 85.000",
    type: "drink",
  },
  {
    id: 22,
    title: "کافه گلاسه",
    description: "بستنی وانیل + قهوه + شیر",
    price: "70.000",
    type: "drink",
  },
  {
    id: 23,
    title: "بستنی اسکوپ",
    description: null,
    price: "20.000",
    type: "drink",
  },
  {
    id: 24,
    title: "کیک بستنی",
    description: null,
    price: "85.000",
    type: "drink",
  },
  {
    id: 25,
    title: "کیک شکلاتی",
    description: null,
    price: "بپرسید",
    type: "drink",
  },
  {
    id: 27,
    title: "ماروچینو",
    description: "اسپرسو + هات چاکلت",
    price: "70.000",
    type: "chocolate",
  },
];
